/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(console_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(73f02af24f9f7a6b7eb84a8ffbbff3d9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nvwa/console_sink.h>
// pydoc.h is automatically generated in the build directory
#include <console_sink_pydoc.h>

void bind_console_sink(py::module& m)
{

    using console_sink    = gr::nvwa::console_sink;


    py::class_<console_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<console_sink>>(m, "console_sink", D(console_sink))

        .def(py::init(&console_sink::make),
           D(console_sink,make)
        )
        



        ;




}








