/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fsp_splitter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c40ecf708ce09d7f2dab81a72afbd5fa)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nvwa/fsp_splitter.h>
// pydoc.h is automatically generated in the build directory
#include <fsp_splitter_pydoc.h>

void bind_fsp_splitter(py::module& m)
{

    using fsp_splitter    = gr::nvwa::fsp_splitter;


    py::class_<fsp_splitter, gr::block, gr::basic_block,
        std::shared_ptr<fsp_splitter>>(m, "fsp_splitter", D(fsp_splitter))

        .def(py::init(&fsp_splitter::make),
           D(fsp_splitter,make)
        )
        



        ;




}








